/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.java.coffeeshop.frames;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;

import com.java.coffeeshop.relativepath.RelativePath;

/**
 *
 * @author felip
 */
public class ListProducts extends javax.swing.JInternalFrame implements FrameManagement {

    /**
     * Creates new form ListProducts
     */
    public ListProducts() {
        initComponents();
    }

    RelativePath relativePath = new RelativePath();

    int stockSize = 50;

    String s;
    String[][] r = new String[stockSize][5];

    public void readData() {

        File file = new File(
                relativePath.getPath() + "/coffeeshop/src/main/java/com/java/coffeeshop/frames/estoque_db.txt");
        String path = file.getPath();

        try {

            BufferedReader reader = new BufferedReader(new FileReader(path));

            int i = 0;

            do {

                s = reader.readLine();

                if (s != null) {

                    String[] w = s.split(";");

                    for (int j = 0; j < w.length; j++) {

                        r[i][j] = w[j];

                    }

                }

                i++;

            } while (s != null);

            reader.close();

        } catch (Exception e) {

            s = "Erro de Leitura";

        }

    }

    public void setTableData() {

        int[] row = new int[stockSize];
        int[] col = new int[5];

        readData();

        System.out.println(s);

        int i = 0;
        int j = 0;

        for (i = 0; i < row.length; i++) {

            for (j = 0; j < col.length; j++) {

                row[i] = i;
                col[j] = j;

                productTable.setValueAt(r[i][j], row[i], col[j]);

            }

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        productTable = new javax.swing.JTable();

        setClosable(true);
        setFrameIcon(new javax.swing.ImageIcon(relativePath.getPath() + "/coffeeshop/images/coffeeshop.png")); // NOI18N
        setMinimumSize(new java.awt.Dimension(1280, 664));
        setPreferredSize(new java.awt.Dimension(1280, 664));
        try {
            setSelected(true);
        } catch (java.beans.PropertyVetoException e1) {
            e1.printStackTrace();
        }
        setVisible(true);

        productTable.setBackground(new java.awt.Color(245, 240, 253));
        productTable.setModel(new javax.swing.table.DefaultTableModel(new Object[][] { { null, null, null, null, null },
                { null, null, null, null, null }, { null, null, null, null, null }, { null, null, null, null, null },
                { null, null, null, null, null }, { null, null, null, null, null }, { null, null, null, null, null },
                { null, null, null, null, null }, { null, null, null, null, null }, { null, null, null, null, null },
                { null, null, null, null, null }, { null, null, null, null, null }, { null, null, null, null, null },
                { null, null, null, null, null }, { null, null, null, null, null }, { null, null, null, null, null },
                { null, null, null, null, null }, { null, null, null, null, null }, { null, null, null, null, null },
                { null, null, null, null, null }, { null, null, null, null, null }, { null, null, null, null, null },
                { null, null, null, null, null }, { null, null, null, null, null }, { null, null, null, null, null },
                { null, null, null, null, null }, { null, null, null, null, null }, { null, null, null, null, null },
                { null, null, null, null, null }, { null, null, null, null, null }, { null, null, null, null, null },
                { null, null, null, null, null }, { null, null, null, null, null }, { null, null, null, null, null },
                { null, null, null, null, null }, { null, null, null, null, null }, { null, null, null, null, null },
                { null, null, null, null, null }, { null, null, null, null, null }, { null, null, null, null, null },
                { null, null, null, null, null }, { null, null, null, null, null }, { null, null, null, null, null },
                { null, null, null, null, null }, { null, null, null, null, null }, { null, null, null, null, null },
                { null, null, null, null, null }, { null, null, null, null, null }, { null, null, null, null, null },
                { null, null, null, null, null }, { null, null, null, null, null }, { null, null, null, null, null },
                { null, null, null, null, null }, { null, null, null, null, null }, { null, null, null, null, null },
                { null, null, null, null, null }, { null, null, null, null, null }, { null, null, null, null, null },
                { null, null, null, null, null }, { null, null, null, null, null }, { null, null, null, null, null },
                { null, null, null, null, null }, { null, null, null, null, null }, { null, null, null, null, null },
                { null, null, null, null, null }, { null, null, null, null, null }, { null, null, null, null, null },
                { null, null, null, null, null }, { null, null, null, null, null }, { null, null, null, null, null },
                { null, null, null, null, null }, { null, null, null, null, null }, { null, null, null, null, null },
                { null, null, null, null, null }, { null, null, null, null, null }, { null, null, null, null, null },
                { null, null, null, null, null }, { null, null, null, null, null }, { null, null, null, null, null },
                { null, null, null, null, null }, { null, null, null, null, null }, { null, null, null, null, null },
                { null, null, null, null, null }, { null, null, null, null, null }, { null, null, null, null, null },
                { null, null, null, null, null }, { null, null, null, null, null }, { null, null, null, null, null },
                { null, null, null, null, null }, { null, null, null, null, null }, { null, null, null, null, null },
                { null, null, null, null, null }, { null, null, null, null, null }, { null, null, null, null, null },
                { null, null, null, null, null }, { null, null, null, null, null }, { null, null, null, null, null },
                { null, null, null, null, null }, { null, null, null, null, null }, { null, null, null, null, null } },
                new String[] { "Id", "Nome", "Valor", "Categoria", "Quantidade" }));
        productTable.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        productTable.setEnabled(false);
        productTable.setGridColor(new java.awt.Color(87, 25, 202));
        productTable.setMaximumSize(new java.awt.Dimension(300, 64));
        productTable.setShowHorizontalLines(false);
        productTable.getTableHeader().setResizingAllowed(false);
        productTable.getTableHeader().setReorderingAllowed(false);
        setTableData();
        jScrollPane2.setViewportView(productTable);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 1264, Short.MAX_VALUE));
        layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 665, Short.MAX_VALUE));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable productTable;
    // End of variables declaration//GEN-END:variables
}
