/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package src.main.java.com.java.coffeeshop.frames;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;

/**
 *
 * @author sucrilho boladao
 */
public class MainFrame extends javax.swing.JFrame implements FrameManagement {

        /**
         * Creates new form MainFrame
         */
        public MainFrame() {
                initComponents();
        }

        String s;
        String[][] r = new String[50][4];

        public void readData() {

                File file = new File(
                                "/home/felipe/DEV/Java-Scripts/coffeeshop/src/main/java/com/java/coffeeshop/estoque_db.txt");
                String path = file.getPath();

                try {

                        BufferedReader reader = new BufferedReader(new FileReader(path));

                        int i = 0;

                        do {

                                s = reader.readLine();

                                if (s != null) {

                                        String[] w = s.split(";");

                                        for (int j = 0; j < w.length; j++) {

                                                r[i][j] = w[j];

                                        }

                                }

                                i++;

                        } while (s != null);

                        reader.close();

                } catch (Exception e) {

                        s = "Erro de Leitura";

                }

        }

        public void writeDate(String input) {

                String path = "estoque_db.txt";

                try {

                        BufferedWriter writer = new BufferedWriter(new FileWriter(path, true));
                        writer.append("");
                        writer.append(input + "\n");

                        writer.close();

                } catch (Exception e) {

                        System.out.println("Erro ao escrever em Estoque Database");

                }

        }

        public void setTableData() {

                int[] row = new int[4];
                int[] col = new int[4];

                readData();

                System.out.println(s);

                int i = 0;
                int j = 0;

                for (i = 0; i < col.length; i++) {

                        for (j = 0; j < row.length; j++) {

                                row[i] = i;
                                col[j] = j;

                                products_list.setValueAt(r[i][j], row[i], col[j]);

                        }

                }

        }

        /**
         * This method is called from within the constructor to initialize the form.
         * WARNING: Do NOT modify this code. The content of this method is always
         * regenerated by the Form Editor.
         */
        @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated
        // Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                background = new javax.swing.JPanel();
                title = new javax.swing.JPanel();
                jLabel1 = new javax.swing.JLabel();
                sidebar = new javax.swing.JPanel();
                btn_products = new javax.swing.JPanel();
                jLabel2 = new javax.swing.JLabel();
                jSeparator1 = new javax.swing.JSeparator();
                btn_products1 = new javax.swing.JPanel();
                jLabel3 = new javax.swing.JLabel();
                btn_products2 = new javax.swing.JPanel();
                jLabel4 = new javax.swing.JLabel();
                logoContainer = new javax.swing.JPanel();
                jLabel7 = new javax.swing.JLabel();
                productsContainer = new javax.swing.JPanel();
                productsContainer.setVisible(false);
                btn_listproducts = new javax.swing.JPanel();
                jLabel6 = new javax.swing.JLabel();
                jScrollPane1 = new javax.swing.JScrollPane();
                products_list = new javax.swing.JTable();

                bottomBar = new javax.swing.JPanel();
                jLabel5 = new javax.swing.JLabel();

                setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
                setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
                setLocation(new java.awt.Point(640, 200));
                setMinimumSize(new java.awt.Dimension(800, 600));
                setPreferredSize(new java.awt.Dimension(1280, 720));
                setResizable(false);

                background.setBackground(new java.awt.Color(87, 25, 202));
                background.setMinimumSize(new java.awt.Dimension(800, 600));
                background.setPreferredSize(new java.awt.Dimension(1280, 576));

                title.setBackground(new java.awt.Color(149, 128, 255));
                title.setMaximumSize(new java.awt.Dimension(433, 44));
                title.setMinimumSize(new java.awt.Dimension(433, 44));

                jLabel1.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
                jLabel1.setForeground(new java.awt.Color(245, 240, 253));
                jLabel1.setText("COFFEESHOP");

                javax.swing.GroupLayout titleLayout = new javax.swing.GroupLayout(title);
                title.setLayout(titleLayout);
                titleLayout.setHorizontalGroup(
                                titleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(titleLayout.createSequentialGroup().addGap(427, 427, 427)
                                                                .addComponent(jLabel1)
                                                                .addContainerGap(501, Short.MAX_VALUE)));
                titleLayout.setVerticalGroup(titleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                                                titleLayout.createSequentialGroup().addComponent(jLabel1).addGap(0, 0,
                                                                Short.MAX_VALUE)));

                sidebar.setBackground(new java.awt.Color(100, 64, 207));
                sidebar.setMaximumSize(new java.awt.Dimension(600, 136));
                sidebar.setMinimumSize(new java.awt.Dimension(136, 100));
                sidebar.setPreferredSize(new java.awt.Dimension(100, 100));

                btn_products.setBackground(new java.awt.Color(149, 128, 255));
                btn_products.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
                btn_products.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseClicked(java.awt.event.MouseEvent evt) {
                                btn_productsMouseClicked(evt);
                        }
                });

                jLabel2.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
                jLabel2.setForeground(new java.awt.Color(245, 240, 253));
                jLabel2.setText("Produtos");

                javax.swing.GroupLayout btn_productsLayout = new javax.swing.GroupLayout(btn_products);
                btn_products.setLayout(btn_productsLayout);
                btn_productsLayout.setHorizontalGroup(
                                btn_productsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(btn_productsLayout.createSequentialGroup().addGap(41, 41, 41)
                                                                .addComponent(jLabel2)
                                                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                Short.MAX_VALUE)));
                btn_productsLayout.setVerticalGroup(btn_productsLayout
                                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(jLabel2,
                                                javax.swing.GroupLayout.Alignment.TRAILING,
                                                javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE));

                jSeparator1.setBackground(new java.awt.Color(245, 240, 253));

                btn_products1.setBackground(new java.awt.Color(149, 128, 255));
                btn_products1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
                btn_products1.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseClicked(java.awt.event.MouseEvent evt) {
                                btn_products1MouseClicked(evt);
                        }
                });

                jLabel3.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
                jLabel3.setForeground(new java.awt.Color(245, 240, 253));
                jLabel3.setText("Clientes");

                javax.swing.GroupLayout btn_products1Layout = new javax.swing.GroupLayout(btn_products1);
                btn_products1.setLayout(btn_products1Layout);
                btn_products1Layout.setHorizontalGroup(
                                btn_products1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(btn_products1Layout.createSequentialGroup().addGap(41, 41, 41)
                                                                .addComponent(jLabel3)
                                                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                Short.MAX_VALUE)));
                btn_products1Layout.setVerticalGroup(btn_products1Layout
                                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(jLabel3,
                                                javax.swing.GroupLayout.Alignment.TRAILING,
                                                javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE));

                btn_products2.setBackground(new java.awt.Color(149, 128, 255));
                btn_products2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
                btn_products2.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseClicked(java.awt.event.MouseEvent evt) {
                                btn_products2MouseClicked(evt);
                        }
                });

                jLabel4.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
                jLabel4.setForeground(new java.awt.Color(245, 240, 253));
                jLabel4.setText("Estoque");

                javax.swing.GroupLayout btn_products2Layout = new javax.swing.GroupLayout(btn_products2);
                btn_products2.setLayout(btn_products2Layout);
                btn_products2Layout.setHorizontalGroup(
                                btn_products2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(btn_products2Layout.createSequentialGroup().addGap(41, 41, 41)
                                                                .addComponent(jLabel4)
                                                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                Short.MAX_VALUE)));
                btn_products2Layout.setVerticalGroup(btn_products2Layout
                                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(jLabel4,
                                                javax.swing.GroupLayout.Alignment.TRAILING,
                                                javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE));

                jLabel7.setText("LOGO");

                javax.swing.GroupLayout logoContainerLayout = new javax.swing.GroupLayout(logoContainer);
                logoContainer.setLayout(logoContainerLayout);
                logoContainerLayout.setHorizontalGroup(
                                logoContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(logoContainerLayout.createSequentialGroup().addGap(22, 22, 22)
                                                                .addComponent(jLabel7)
                                                                .addContainerGap(26, Short.MAX_VALUE)));
                logoContainerLayout.setVerticalGroup(logoContainerLayout
                                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                                                logoContainerLayout.createSequentialGroup()
                                                                .addContainerGap(31, Short.MAX_VALUE)
                                                                .addComponent(jLabel7).addGap(28, 28, 28)));

                javax.swing.GroupLayout sidebarLayout = new javax.swing.GroupLayout(sidebar);
                sidebar.setLayout(sidebarLayout);
                sidebarLayout.setHorizontalGroup(sidebarLayout
                                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(btn_products, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btn_products1, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btn_products2, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(sidebarLayout.createSequentialGroup().addContainerGap()
                                                .addComponent(jSeparator1).addContainerGap())
                                .addGroup(sidebarLayout.createSequentialGroup().addGap(28, 28, 28)
                                                .addComponent(logoContainer, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addContainerGap(32, Short.MAX_VALUE)));
                sidebarLayout.setVerticalGroup(sidebarLayout
                                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(sidebarLayout.createSequentialGroup().addContainerGap()
                                                .addComponent(logoContainer, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(19, 19, 19)
                                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(14, 14, 14)
                                                .addComponent(btn_products, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(btn_products1, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(btn_products2, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                Short.MAX_VALUE)));

                productsContainer.setBackground(new java.awt.Color(100, 64, 207));

                btn_listproducts.setBackground(new java.awt.Color(149, 128, 255));
                btn_listproducts.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
                btn_listproducts.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseClicked(java.awt.event.MouseEvent evt) {
                                btn_listproductsMouseClicked(evt);
                        }
                });

                jLabel6.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
                jLabel6.setForeground(new java.awt.Color(245, 240, 253));
                jLabel6.setText("Produtos Cadastrados");

                javax.swing.GroupLayout btn_listproductsLayout = new javax.swing.GroupLayout(btn_listproducts);
                btn_listproducts.setLayout(btn_listproductsLayout);
                btn_listproductsLayout.setHorizontalGroup(btn_listproductsLayout
                                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(btn_listproductsLayout.createSequentialGroup().addContainerGap()
                                                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addContainerGap()));
                btn_listproductsLayout.setVerticalGroup(btn_listproductsLayout
                                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(btn_listproductsLayout.createSequentialGroup().addContainerGap()
                                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 14,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                Short.MAX_VALUE)));

                products_list.setAutoCreateRowSorter(true);
                products_list.setBackground(new java.awt.Color(245, 240, 253));
                products_list.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
                products_list.setForeground(new java.awt.Color(46, 13, 98));
                products_list.setModel(new javax.swing.table.DefaultTableModel(
                                new Object[][] { { null, null, null, null }, { null, null, null, null },
                                                { null, null, null, null }, { null, null, null, null } },
                                new String[] { "Nome", "Preco", "Categoria", "Quantidade" }));
                products_list.setEnabled(false);
                products_list.setGridColor(new java.awt.Color(46, 13, 98));
                products_list.setOpaque(false);
                products_list.setSelectionBackground(new java.awt.Color(149, 128, 255));
                products_list.setSelectionForeground(new java.awt.Color(149, 128, 255));
                products_list.setShowGrid(false);
                products_list.getTableHeader().setResizingAllowed(false);
                products_list.getTableHeader().setReorderingAllowed(false);
                jScrollPane1.setViewportView(products_list);

                javax.swing.GroupLayout productsContainerLayout = new javax.swing.GroupLayout(productsContainer);
                productsContainer.setLayout(productsContainerLayout);
                productsContainerLayout.setHorizontalGroup(productsContainerLayout
                                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(productsContainerLayout.createSequentialGroup().addContainerGap()
                                                .addGroup(productsContainerLayout.createParallelGroup(
                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                                .addGroup(productsContainerLayout
                                                                                .createSequentialGroup()
                                                                                .addComponent(btn_listproducts,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addGap(0, 0, Short.MAX_VALUE))
                                                                .addComponent(jScrollPane1))
                                                .addContainerGap()));
                productsContainerLayout.setVerticalGroup(productsContainerLayout
                                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(productsContainerLayout.createSequentialGroup().addContainerGap()
                                                .addComponent(btn_listproducts, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 91,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addContainerGap(61, Short.MAX_VALUE)));

                bottomBar.setBackground(new java.awt.Color(245, 240, 253));

                jLabel5.setFont(new java.awt.Font("Calibri", 1, 10)); // NOI18N
                jLabel5.setForeground(new java.awt.Color(46, 13, 98));
                jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                jLabel5.setText("Designed by Sucrilho Boladao");
                jLabel5.setAlignmentY(0.0F);
                jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

                javax.swing.GroupLayout bottomBarLayout = new javax.swing.GroupLayout(bottomBar);
                bottomBar.setLayout(bottomBarLayout);
                bottomBarLayout.setHorizontalGroup(
                                bottomBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(bottomBarLayout.createSequentialGroup().addGap(461, 461, 461)
                                                                .addComponent(jLabel5)
                                                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                Short.MAX_VALUE)));
                bottomBarLayout.setVerticalGroup(
                                bottomBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));

                javax.swing.GroupLayout backgroundLayout = new javax.swing.GroupLayout(background);
                background.setLayout(backgroundLayout);
                backgroundLayout.setHorizontalGroup(backgroundLayout
                                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(backgroundLayout.createSequentialGroup()
                                                .addComponent(sidebar, javax.swing.GroupLayout.PREFERRED_SIZE, 136,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addGroup(backgroundLayout.createParallelGroup(
                                                                javax.swing.GroupLayout.Alignment.LEADING, false)
                                                                .addComponent(title,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                Short.MAX_VALUE)
                                                                .addComponent(bottomBar,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                Short.MAX_VALUE)
                                                                .addComponent(productsContainer,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                Short.MAX_VALUE))
                                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                Short.MAX_VALUE)));
                backgroundLayout.setVerticalGroup(backgroundLayout
                                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(backgroundLayout.createSequentialGroup().addContainerGap()
                                                .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, 33,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(productsContainer, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(bottomBar, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(sidebar, javax.swing.GroupLayout.DEFAULT_SIZE, 720, Short.MAX_VALUE));

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(background, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE));
                layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, 720, Short.MAX_VALUE));

                pack();
        }// </editor-fold>//GEN-END:initComponents

        private void btn_productsMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_btn_productsMouseClicked
                // TODO add your handling code here:
                productsContainer.setVisible(true);
                btn_products.setBackground(new java.awt.Color(137, 79, 231));

                btn_products1.setBackground(new java.awt.Color(149, 128, 255));
                btn_products2.setBackground(new java.awt.Color(149, 128, 255));

        }// GEN-LAST:event_btn_productsMouseClicked

        private void btn_products1MouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_btn_products1MouseClicked
                // TODO add your handling code here:
                btn_products1.setBackground(new java.awt.Color(137, 79, 231));

                productsContainer.setVisible(false);
                btn_products.setBackground(new java.awt.Color(149, 128, 255));
                btn_products2.setBackground(new java.awt.Color(149, 128, 255));

        }// GEN-LAST:event_btn_products1MouseClicked

        private void btn_products2MouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_btn_products2MouseClicked
                // TODO add your handling code here:
                btn_products2.setBackground(new java.awt.Color(137, 79, 231));

                productsContainer.setVisible(false);
                btn_products.setBackground(new java.awt.Color(149, 128, 255));
                btn_products1.setBackground(new java.awt.Color(149, 128, 255));

        }// GEN-LAST:event_btn_products2MouseClicked

        private void btn_listproductsMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_btn_listproductsMouseClicked
                // TODO add your handling code here:

                setTableData();

        }// GEN-LAST:event_btn_listproductsMouseClicked

        /**
         * @param args the command line arguments
         */
        public static void main(String args[]) {
                /* Set the Nimbus look and feel */
                // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
                // (optional) ">
                /*
                 * If Nimbus (introduced in Java SE 6) is not available, stay with the default
                 * look and feel. For details see
                 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
                 */
                try {
                        for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager
                                        .getInstalledLookAndFeels()) {
                                if ("Nimbus".equals(info.getName())) {
                                        javax.swing.UIManager.setLookAndFeel(info.getClassName());
                                        break;
                                }
                        }
                } catch (ClassNotFoundException ex) {
                        java.util.logging.Logger.getLogger(MainFrame.class.getName())
                                        .log(java.util.logging.Level.SEVERE, null, ex);
                } catch (InstantiationException ex) {
                        java.util.logging.Logger.getLogger(MainFrame.class.getName())
                                        .log(java.util.logging.Level.SEVERE, null, ex);
                } catch (IllegalAccessException ex) {
                        java.util.logging.Logger.getLogger(MainFrame.class.getName())
                                        .log(java.util.logging.Level.SEVERE, null, ex);
                } catch (javax.swing.UnsupportedLookAndFeelException ex) {
                        java.util.logging.Logger.getLogger(MainFrame.class.getName())
                                        .log(java.util.logging.Level.SEVERE, null, ex);
                }
                // </editor-fold>

                /* Create and display the form */
                java.awt.EventQueue.invokeLater(new Runnable() {
                        public void run() {
                                new MainFrame().setVisible(true);
                        }
                });
        }

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JPanel background;
        private javax.swing.JPanel bottomBar;
        private javax.swing.JPanel btn_listproducts;
        private javax.swing.JPanel btn_products;
        private javax.swing.JPanel btn_products1;
        private javax.swing.JPanel btn_products2;
        private javax.swing.JLabel jLabel1;
        private javax.swing.JLabel jLabel2;
        private javax.swing.JLabel jLabel3;
        private javax.swing.JLabel jLabel4;
        private javax.swing.JLabel jLabel5;
        private javax.swing.JLabel jLabel6;
        private javax.swing.JLabel jLabel7;
        private javax.swing.JScrollPane jScrollPane1;
        private javax.swing.JSeparator jSeparator1;
        private javax.swing.JPanel logoContainer;
        private javax.swing.JPanel productsContainer;
        private javax.swing.JTable products_list;
        private javax.swing.JPanel sidebar;
        private javax.swing.JPanel title;
        // End of variables declaration//GEN-END:variables
}
